version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    environment:
      - FLASK_ENV=development
    ports:
      - "8081:8081"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web