"""Add count column to applications table

Revision ID: 89152c2b5522
Revises: 
Create Date: 2024-12-17 01:00:13.392506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89152c2b5522'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aplications', schema=None) as batch_op:
        batch_op.drop_column('count')

    # ### end Alembic commands ###
