"""6 migration.

Revision ID: 14d8cf62b6b4
Revises: f9a06ee740af
Create Date: 2024-12-30 04:02:40.824268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d8cf62b6b4'
down_revision = 'f9a06ee740af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_aplication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.String(length=128), nullable=False))
        batch_op.drop_column('apl_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_aplication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apl_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('item_name')
        batch_op.drop_column('user_id')
        batch_op.drop_column('item_id')
        batch_op.drop_column('quantity')
        batch_op.drop_column('status')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
