"""5 migration.

Revision ID: f9a06ee740af
Revises: 
Create Date: 2024-12-30 03:26:37.985575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9a06ee740af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_aplication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apl_id', sa.Integer(), nullable=False))
        batch_op.drop_column('apl')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('return_aplication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apl', sa.INTEGER(), nullable=False))
        batch_op.drop_column('apl_id')

    # ### end Alembic commands ###
